version: '3.8'

services:
  order-service:
    build: ./php-order-service
    environment:
      - PRODUCT_SERVICE_URL=http://product-service:8080
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=order_service
    depends_on:
      mysql:
        condition: service_healthy
    command: >
      sh -c "sleep 10 && php src/init-db.php && php-fpm"
    restart: unless-stopped
    volumes:
      - ./php-order-service/public:/var/www/public
      - ./php-order-service/src:/var/www/src
      - ./php-order-service/vendor:/var/www/vendor

  nginx-order:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./php-order-service/docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./php-order-service/public:/var/www/public
    depends_on:
      - order-service

  product-service:
    build: ./node-product-service
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=product_service
      - SERVICE_PORT=8080
    depends_on:
      mysql:
        condition: service_healthy
    command: >
      sh -c "sleep 10 && npm run dev"
    restart: unless-stopped
    volumes:
      - ./node-product-service/src:/app/src
      - ./node-product-service/node_modules:/app/node_modules

  mysql:
    image: mysql:8.2
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=product_service
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-authentication-plugin=mysql_native_password
      --init-file=/docker-entrypoint-initdb.d/init.sql
      --skip-name-resolve
      --skip-host-cache

volumes:
  mysql-data: 