<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPKdSIF9\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPKdSIF9/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerPKdSIF9.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerPKdSIF9\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerPKdSIF9\App_KernelProdContainer([
    'container.build_hash' => 'PKdSIF9',
    'container.build_id' => '3e4efbc5',
    'container.build_time' => 1744815199,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPKdSIF9');
