services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Application services
    App\:
        resource: '../src/*'
        exclude: '../src/{DTO,HttpClient}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\HttpClient\ProductClient:
        class: App\HttpClient\ProductClient
        arguments:
            $baseUrl: '%env(PRODUCT_SERVICE_URL)%'

    App\Storage\OrderStorage:
        class: App\Storage\OrderStorage

    App\Service\OrderService:
        class: App\Service\OrderService
        arguments:
            $productClient: '@App\HttpClient\ProductClient'
            $orderStorage: '@App\Storage\OrderStorage'

    App\Storage\Database: ~
