<?php

namespace ContainerPKdSIF9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\OrderController' shared autowired service.
     *
     * @return \App\Controller\OrderController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['App\\Controller\\OrderController'] = new \App\Controller\OrderController(new \App\Service\OrderService(new \App\HttpClient\ProductClient($container->getEnv('PRODUCT_SERVICE_URL')), new \App\Storage\OrderStorage()), ($container->privates['serializer'] ?? self::getSerializerService($container)), ($container->privates['validator'] ?? self::getValidatorService($container)));
    }
}
